[SHIP-545] Auto-create requirements.txt if missing (#280)
This only adds the steamship dependency, though, so you may still
encounter an error if you need other deps.

If you have another dep you don't put in the requirements, you'll get an
error message like:

```
Deploying version 0.0.1-rc.2 of [dave-testy-testeroo]... 🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢
Unable to create / fetch package.
Server returned message: There was an error loading the main file (it must be named api.py):
Traceback (most recent call last):
  File "/var/task/steamship/invocable/lambda_handler.py", line 274, in safely_find_invocable_class
    module = importlib.import_module("api")
  File "/var/lang/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/api.py", line 2, in <module>
    import pandas
ModuleNotFoundError: No module named 'pandas'
It looks like you may be missing a dependency in your requirements.txt.
Aborted!
```

---------

Co-authored-by: Ted Benson <edward.benson@gmail.com>